# Generated by Django 3.1.1 on 2020-10-19 18:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
                ('population', models.IntegerField(verbose_name='Population')),
                ('image', models.ImageField(upload_to='camp_pictures', verbose_name='Camp Picture')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Camp')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Camps',
                'verbose_name_plural': 'Camps',
            },
        ),
    ]
