# Generated by Django 3.1.1 on 2020-10-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0002_camps'),
    ]

    operations = [
        migrations.AddField(
            model_name='camps',
            name='commissoned',
            field=models.DateTimeField(auto_now=True, verbose_name='Commision Date'),
        ),
        migrations.AddField(
            model_name='camps',
            name='decomissioned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Decomission Date'),
        ),
    ]
