# Generated by Django 3.1.1 on 2020-10-21 10:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0003_auto_20201020_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('description', models.TextField(verbose_name='Point Description')),
                ('image', models.ImageField(blank=True, upload_to='user_location', verbose_name='Location Image')),
            ],
            options={
                'verbose_name': 'UserLocation',
                'verbose_name_plural': 'UserLocations',
            },
        ),
        migrations.AlterField(
            model_name='camps',
            name='image',
            field=models.ImageField(default='ee.PNG', upload_to='camp_pictures', verbose_name='Camp Picture'),
        ),
    ]
